dimagi/commcare-connect

commcare_connect/opportunity/admin.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_create.html, commcare_connect/templates/opportunity/opportunity_list.html, config/urls.py
1. Opportunity List
2. Opportunity Create
3. Opportunity Edit
=> UI for Listing, Creating and Editing Opportunities

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py, config/api_router.py
=> Add API for getting opportunity details for CID Users

commcare_connect/conftest.py, commcare_connect/form_receiver/apps.py, commcare_connect/form_receiver/const.py, commcare_connect/form_receiver/exceptions.py, commcare_connect/form_receiver/processor.py, commcare_connect/form_receiver/serializers.py, commcare_connect/form_receiver/tests/test_receiver.py, commcare_connect/form_receiver/tests/xforms.py, commcare_connect/form_receiver/views.py, config/api_router.py, config/settings/base.py, requirements/base.in, requirements/base.txt, requirements/dev.txt
This endpoint will receive requests from the CommCare HQ form forwarders.
Current the code just extracts the CCC blocks from the form JSON but doesn't actually do anything with it.
=> initial code for the 'receiver' endpoint

config/settings/base.py, config/settings/local.py, config/settings/production.py, config/settings/staging.py, config/settings/test.py
=> update logging, cleanup settings, configure sentry

commcare_connect/opportunity/admin.py, commcare_connect/opportunity/app_xml.py, commcare_connect/opportunity/forms.py, commcare_connect/opportunity/models.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_app_xml.py, commcare_connect/opportunity/views.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-93)
=> Save metadata from CC App to Database

commcare_connect/opportunity/models.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/static/sass/project.scss, commcare_connect/templates/base.html, commcare_connect/templates/opportunity/learn_progress.html, commcare_connect/templates/opportunity/opportunity_list.html, commcare_connect/templates/opportunity/user_learn_progress.html, commcare_connect/users/signals.py
[Ticket Link](https://dimagi-dev.atlassian.net/browse/CCPC-95)
Learn Progress:
User Specific Learn Progress:
=> UI for Learn Progress Data

commcare_connect/opportunity/api/views.py, config/api_router.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-96)
This PR includes filtering for opportunities on Opportunity API based on the OpporunityAccess model.
=> Opportunity filtering in opportunity API

.ebextensions/01-celery.config, .platform/hooks/postdeploy/01-celery-start.sh
Following guides:
* https://gist.github.com/MahirMahbub/f9c226dbc0a01da22c8c539cf9c9bcc9
* https://gist.github.com/Alex3917/9b09e67069c88361d4e0187e1968bc64
* https://www.linkedin.com/pulse/deploying-django-celery-amazon-sqs-aws-elastic-beanstalk-mahir-mahbub/
May require some tweaking
=> configure celery service

commcare_connect/organization/decorators.py, commcare_connect/organization/forms.py, commcare_connect/organization/models.py, commcare_connect/organization/urls.py, commcare_connect/organization/views.py, commcare_connect/static/sass/project.scss, commcare_connect/templates/base.html, commcare_connect/templates/organization/organization_home.html, commcare_connect/web/templatetags/active_link.py, config/urls.py
=> Organization details view

commcare_connect/opportunity/app_xml.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-100)
=> Add CCHQ app fetch using all latest params

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py, config/api_router.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-102)
=> Add endpoint to fetch learn progress data for a user

commcare_connect/templates/opportunity/opportunity_detail.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-104)
=> Add learn modules to Opportunity Details UI

commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_create.html, commcare_connect/templates/opportunity/opportunity_detail.html, commcare_connect/templates/opportunity/opportunity_edit.html, commcare_connect/templates/opportunity/opportunity_list.html, commcare_connect/templates/organization/organization_home.html
=> UI improvements for Opportunity List page

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py, config/api_router.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-105)
=> User Visits Verification Status api endpoint

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/views.py, config/settings/base.py
=> few tweaks to adding users to opportunities

config/urls.py
I forgot to add these when I added the `oauth2_provider` app
=> add oauth toolkit urls

.github/workflows/deploy.yml
=> deploy slack notifications

commcare_connect/opportunity/export.py, commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_export.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_detail.html, commcare_connect/templates/opportunity/upload_progress.html
=> export filtering and move export to celery task

commcare_connect/conftest.py, commcare_connect/form_receiver/processor.py, commcare_connect/form_receiver/serializers.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/users/tests/factories.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-97)
=> Assign correct user during form processing

commcare_connect/opportunity/tasks.py
Found this bug when I was testing out the add user workflows
=> unpack tuple

commcare_connect/form_receiver/processor.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/users/tests/factories.py
https://dimagi-dev.atlassian.net/browse/CCPC-97
=> format commcare username from xform

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-114)
=> Update Learn Progress api to list all completed modules

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_detail.html, commcare_connect/templates/opportunity/opportunity_list.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-111)
Updated Dropdown with opportunity details view options
=> Claims: Add form and view to add budget for new users

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-115)
=> Update opportunity api to include user progress and learn info 

.github/workflows/deploy.yml, deploy/README.md, tasks.py
https://github.com/basecamp/kamal/releases/tag/v1.0.0
=> upgrade kamal to 1.0

commcare_connect/users/views.py
this argument was removed in https://github.com/dimagi/commcare-connect/commit/8084857726c010dbf050d3347f7535b5a6ff066d
=> removed deprecated arg

commcare_connect/opportunity/tasks.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-132)
=> Fix duplicate learn modules created on submitting forms

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py
This is why tests are important
=> use serializer data and retrieve view

commcare_connect/opportunity/api/serializers.py
This was overlooked in https://github.com/dimagi/commcare-connect/pull/139
=> update delivery progress api to use deliver units

commcare_connect/opportunity/tasks.py
=> Fix payment export encode csv exports

commcare_connect/opportunity/app_xml.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_detail.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-137)
https://github.com/dimagi/commcare-connect/assets/31195143/bb9c166f-f96a-4c11-aa0a-38a3634767c3
Deliver Units Table:
=> Add deliver units to opportunity detail UI, accordion for Learn Modules and Deliver units

commcare_connect/opportunity/api/serializers.py
Modules weren't being filtered by user here either
=> filter modules by user

commcare_connect/opportunity/api/serializers.py
Including the new payment info in the relevant APIs
=> update delivery progress api

commcare_connect/templates/opportunity/add_visits_existing_users.html
[Bug Ticket](https://dimagi-dev.atlassian.net/browse/QA-5756)
=> Add name to the add visit existing users form

commcare_connect/opportunity/api/serializers.py
now that apps come from multiple places, mobile wants an install URL
=> add install url

commcare_connect/users/urls.py
Pretty self explanatory but will possibly help with https://dimagi-dev.atlassian.net/browse/CCPC-179
=> add trailing slash to invite link

commcare_connect/form_receiver/processor.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-199)
=> Fix max visits counting the over_limit visits

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/add_visits_existing_users.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-204)
=> Extend End Date optionally for users on Add budget page

commcare_connect/form_receiver/processor.py, commcare_connect/opportunity/models.py, commcare_connect/opportunity/tests/factories.py, commcare_connect/templates/opportunity/opportunity_list.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-207)
=> Fix mark inactive if past end date

commcare_connect/opportunity/api/serializers.py
Default values did not take effect, so I am taking a more direct approach.
=> use method to set default

deploy/config/deploy.production.yml
turns out Kamal can't use short names
=> use long name and quotes

commcare_connect/form_receiver/processor.py, commcare_connect/opportunity/models.py, commcare_connect/opportunity/tasks.py
[Ticket](https://dimagi-dev.atlassian.net/browse/QA-5846)
This PR makes fixes logic which was excluding the end_date for an opportunity and marking them as inactive.
=> Fix today's end_date marks opportunity inactive

deploy/config/deploy.production.yml, deploy/play.yml, deploy/production.inventory.yml
this adds a new celery machine to handle large exports without impacting the web requests.
=> add dedicated celery machine

commcare_connect/opportunity/tests/test_views.py
Add test for https://github.com/dimagi/commcare-connect/pull/199
=> Add test for add_budget_existing_users view

commcare_connect/opportunity/admin.py, commcare_connect/users/admin.py
Admin list displays are vague for a lot of models which make it hard to debug issues. Added better listing for various models.
=> Admin list for opportunity / user models

commcare_connect/connect_id_client/main.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/visit_import.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-215)
- Added a separate task to send payment notification in order to avoid blocking the user payment import.
- Increased the read timeout for the send message bulk API
=> Fix Payment import failing on sending notification

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/views.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-221)
- Added ordering to the query set
- Refactor view to use the helper method and remove code duplication for deliver status queryset
=> Add user name sorting to Deliver Status Table

commcare_connect/opportunity/export.py, commcare_connect/opportunity/tests/test_export.py
Fix for excel exports failing on datetime objects with timezones.
=> Fix date timezone for export

commcare_connect/opportunity/tasks.py
=> do not prefetch on an instance

commcare_connect/opportunity/tests/test_visit_import.py
- Adds test for bulk_update_payments
=> Add test for bulk_update_payments

commcare_connect/opportunity/forms.py
[Ticket](https://dimagi-dev.atlassian.net/jira/software/projects/CCPC/issues/CCPC-232)
This PR makes some fields editable on the Opportunity.
- Daily Max Visits Per User
- Max Visits Per User
- Short Description
- Currency
=> Editable fields for Opportunity

commcare_connect/opportunity/tests/test_visit_import.py, commcare_connect/opportunity/visit_import.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-222)
=> Fix payment accrual bug

commcare_connect/opportunity/admin.py
This keeps the deletions scoped to the correct opportunity.
=> include opportunity filter

commcare_connect/connect_id_client/main.py, commcare_connect/connect_id_client/models.py, commcare_connect/templates/users/demo_tokens.html, commcare_connect/users/urls.py, commcare_connect/users/views.py
This is the linked connect PR to https://github.com/dimagi/connect-id/pull/12
It creates a view that fetches the OTPs for demo users and shows them to superusers in the connect UI.
=> demo token view

commcare_connect/opportunity/forms.py
[Ticket](https://dimagi.atlassian.net/browse/SUPPORT-18723)
=> Fix add opportunity end_date as initial value

commcare_connect/opportunity/tables.py
=> Fix broken deliver_unit list

commcare_connect/opportunity/views.py
[Ticket](https://dimagi.atlassian.net/browse/QA-6124)
Fixed Payment not getting accrued on visit approval in the verification UI.
=> Fix payment accrued on visit approve from UI

commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/visit_verification.html
Until we get the token into the JS build, use the one in settings
=> use token from view

commcare_connect/static/sass/project.scss, commcare_connect/templates/account/base.html, commcare_connect/templates/account/login.html, commcare_connect/templates/account/signup.html, commcare_connect/templates/base.html, package-lock.json, package.json
🚧 Work in Progress: The pages in this pull request are still rough around the edges. I've initiated the process to enhance the UI, but there's a lot of fine-tuning left to be done.
🎨 Next Steps:
- Adjusting colors to match Dimagi's Color Palette.
- Adjusting paddings for a cleaner layout.
- Centering content for a more polished look.
- Adding icons
This is just the beginning, and I wanted to kick things off. Your feedback is valuable, and I'll be refining these aspects in the upcoming pull requests.
=> Acccount templates - ui enhancement

commcare_connect/templates/opportunity/send_message.html, commcare_connect/templates/opportunity/user_learn_progress.html, commcare_connect/templates/opportunity/visit_verification.html
This addresses UI issues found by QA this morning.
=> add ui fixes from qa

commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/visit_verification.html
Added a legend and fixed the user and status displays.
=> add legend and fix popups

commcare_connect/opportunity/views.py
[Bug Ticket](https://dimagi.atlassian.net/browse/CCCT-270)
=> Fix visit verification page bug

commcare_connect/opportunity/models.py, commcare_connect/templates/opportunity/opportunity_detail.html
[Ticket](https://dimagi.atlassian.net/browse/CCCT-284)
=> Add app url for learn and deliver apps

commcare_connect/opportunity/api/views.py, commcare_connect/opportunity/tests/test_api_views.py
This fixes a syntax error and then adds some tests for the new api and changes to the old one
=> add tests for payment confirmation

commcare_connect/opportunity/api/serializers.py
https://dimagi.atlassian.net/browse/CCCT-307
=> Fix null max_payments on deliver status api

commcare_connect/opportunity/tasks.py
[Ticket](https://dimagi.atlassian.net/browse/QA-6442)
=> Fix auto verification task issue

commcare_connect/opportunity/tasks.py
I think this task can cause issues for celery workers. Adding some logging so we can investigate issues if they arise.
=> add logging for export

deploy/config/deploy.production.yml, deploy/production.inventory.yml
The EC2 instance IP was updated
=> update celery ip

deploy/config/deploy.production.yml, deploy/production.inventory.yml
Changed the celery IP after the recent celery instance size increase.
=> Change celery IP

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tests/test_models.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-347)
=> Fix delivery progress counts

commcare_connect/opportunity/tests/test_export.py, commcare_connect/opportunity/visit_import.py
This PR includes fixes for
- Random test failures in the user data export code. The test was failing due to missing the last visit date column for trial visits.
- Fix the import code not being able to handle spaces in the status column causing the import to fail with errors. "Rejected " made the import fail.
=> Fixes for export related code.

commcare_connect/opportunity/tasks.py
[JIRA Ticket](https://dimagi.atlassian.net/browse/CCCT-361)
=> Added two new fields in data dict for Notification deep link

commcare_connect/opportunity/tables.py
[JIRA Ticket](https://dimagi.atlassian.net/browse/CCCT-367)
=> Refactor render_flag_reason method to correctly format flag reasons

commcare_connect/templates/opportunity/opportunity_user_payments_list.html
[QA Ticket](https://dimagi.atlassian.net/browse/QA-6699)
=> Fix hide rollback payment button for viewers

commcare_connect/users/views.py
This fixes a race condition in accepted status if the invite is accepted before the sms is delivered. It also prevents continually updating the learn start date, if the view is hit multiple times.
=> fix race conditions in invite and accepted status

config/settings/production.py, config/settings/staging.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-365)
This PR adds ignore logger statements to ignore DisallowedHost errors on sentry.
=> Add sentry ignore logs for DisallowedHost errors

commcare_connect/opportunity/tasks.py
https://dimagi.atlassian.net/browse/CCCT-389
=> Error while sending the notifications

commcare_connect/opportunity/visit_import.py
https://dimagi.atlassian.net/browse/CCCT-396
=> Implement Ability to Add Reason to User Visit and Completed Work Regardless of Status Change.

commcare_connect/opportunity/tables.py
https://dimagi.atlassian.net/browse/CCCT-390
=> Add column totals to the Deliver status tab.

commcare_connect/reports/tables.py, commcare_connect/reports/views.py
since so few of the payments are confirmed, this adds a column for all payments to the admin report
=> add total payment data

commcare_connect/opportunity/views.py, commcare_connect/static/js/project.js, commcare_connect/templates/opportunity/user_profile.html
https://dimagi.atlassian.net/browse/CCCT-378
=> Map user catchment areas on the user profile page.

commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/visit_verification.html
[Ticket](https://dimagi.atlassian.net/browse/CCCT-391)
- Added a modal for rejecting user visits with a reason.
- Added some minor UI enhancements.
=> Add Ability to add / edit Rejection reason on User Visit Verification UI

commcare_connect/opportunity/tasks.py
https://dimagi.atlassian.net/browse/CCCT-416
=> Add payment id to payment notification

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/views.py
https://dimagi.atlassian.net/browse/CCCT-405
=> Fix caching bug for suspended users

commcare_connect/opportunity/views.py
[Bug Ticket](https://dimagi.atlassian.net/browse/QA-6881)
=> Fix flag_reason none causing errors

commcare_connect/users/admin.py
https://dimagi.atlassian.net/browse/CCCT-418
=> Added a webuser filter and search by email in user admin page

commcare_connect/organization/forms.py, commcare_connect/organization/views.py, commcare_connect/templates/base.html, commcare_connect/templates/organization/organization_create.html, commcare_connect/users/signals.py, commcare_connect/users/tests/test_views.py, commcare_connect/users/views.py, config/urls.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-417)
=> Create Organization on User Signup

commcare_connect/opportunity/management/commands/auto_approval_opportunities.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/utils/completed_work.py, commcare_connect/opportunity/visit_import.py
https://dimagi.atlassian.net/browse/CCCT-419
=> Management command to run one time auto approval for old opportunities

commcare_connect/utils/sms.py
Connect version of https://github.com/dimagi/connect-id/pull/39
The senderid has been approved on twilio so now we can start using it
=> add moz to sender dict

commcare_connect/reports/views.py, deploy/config/deploy.production.yml, deploy/production.inventory.yml
This view was causing out of memory errors so I added some simple chunking and increased the size of the machine, which caused the ip to change.
=> chunk report and update inventory

requirements/production.in, requirements/production.txt
This is necessary for https://github.com/dimagi/commcare-connect/pull/392
=> add gevent to production requirements

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py
https://dimagi.atlassian.net/browse/QA-7046
Programs Manager, user is unable to access the status on opportunity detail page like payments, visits, deliver etc.
=> Changed Table arguments to avoid forbidden error in case when program manager view opportunity detail page.

commcare_connect/templates/opportunity/opportunity_detail.html
[Sentry Error Link](https://dimagi.sentry.io/issues/5867603718/?environment=production&project=4505635339829248&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true)
=> Fix remove link to removed url

commcare_connect/opportunity/utils/completed_work.py
[Sentry Issue](https://dimagi.sentry.io/issues/5824666226/?environment=production&project=4505635339829248&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true)
=> Fix completed work update_status bug

commcare_connect/connect_id_client/main.py, commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tests/test_forms.py, commcare_connect/opportunity/views.py, commcare_connect/organization/views.py
[CCCT-521](https://dimagi.atlassian.net/browse/CCCT-521)
Needed some changes on connect-id as well [PR-47](https://github.com/dimagi/connect-id/pull/47)
[CCCT-521]: https://dimagi.atlassian.net/browse/CCCT-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Limit Visible Credentials to Organization-Issued Credentials in User Invites

commcare_connect/reports/urls.py, commcare_connect/reports/views.py, commcare_connect/static/js/dashboard.js, commcare_connect/templates/reports/dashboard.html
PR into https://github.com/dimagi/commcare-connect/pull/429
=> Add charts to the dahboard

config/views.py
This PR fixes the linter error that is coming up on the recent PRs.
[Link for the error.](https://github.com/dimagi/commcare-connect/actions/runs/11855706724/job/33040476911)
=> Fix linter error

commcare_connect/opportunity/admin.py, commcare_connect/opportunity/models.py
Added the payment unit model admin with details about payment units and __str__ so that the payment unit name is represented in django admin.
=> Add PaymentUnit model to admin

commcare_connect/opportunity/admin.py
[Sentry Error Link](https://dimagi.sentry.io/issues/6079481711/?environment=production&project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=24h&stream_index=2&utc=true)
=> Fix error in payment unit admin

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_detail.html
[Ticket](https://dimagi.atlassian.net/browse/CCCT-524)
=> User Invite Status Privacy Changes

commcare_connect/templates/reports/dashboard.html
This just tweaks the clustering params on the admin reports.
Tested locally and also is internal dimagi only report.
=> tweak clustering params

commcare_connect/opportunity/admin.py, commcare_connect/reports/views.py, commcare_connect/templates/reports/dashboard.html
This is a PR into https://github.com/dimagi/commcare-connect/pull/471 as it's dependent on that work. It also has everything in https://github.com/dimagi/commcare-connect/pull/465, since that hasn't been merged yet.
Adds FLW/Org earnings and payments to the program dashboard report.
The reporting side of this is pretty straightforward.
This only touches an admin report that very few people know about. So should be safe.
No tests.
Will throw on staging, but shouldn't require any QA before being merged.
=> Payment dashboard updates

commcare_connect/opportunity/admin.py
add admin for PaymentInvoice objects
Just an admin update.
=> add admin for PaymentInvoice objects

commcare_connect/reports/views.py
Adds better number formatting to the dashboard.
Low impact change, admin report only
=> format numbers with commas

commcare_connect/templates/reports/dashboard.html
Makes some updates to the dashboard to improve how it looks on different screen sizes, fix an issue where the charts rendered multiple times, and adds a fullscreen control to the map.
Details in the individual commits.
Still working on an admin-only report, so should be safe.
=> Dashboard polish

commcare_connect/reports/views.py
I was mistaken in the initial requirements and the org earnings should include not just the money that goes to them but the money they pass through to the workers. This updates that.
=> get total for org earnings

commcare_connect/reports/views.py
Changes the program dashboard end date to include the "end date" in queries.
=> make end date inclusive

commcare_connect/reports/views.py
The org earnings were updated to include passthrough funding in https://github.com/dimagi/commcare-connect/pull/484 but payments were not. This does that.
Just some addition
=> include totals for orgs

docker/start, docker/start_migrate
Our workers are getting overwhelmed so wanted to add a few more. This also brings us within gunicorn's recommended number of (2-4)*(num cores), which in our case is 2 cores.
=> add more gunicorn workers

deploy/config/deploy.production.yml
I had to restart web machine and the IP address got changed. I will add Elastic IP so that this doesn't happen in future
=> web address changed on restart

commcare_connect/reports/helpers.py, commcare_connect/reports/tests/test_reports.py, commcare_connect/reports/views.py
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-770)
Tested on staging
Changes are covered under the automated test cases.
=> Add country based filtering to report

commcare_connect/templates/opportunity/opportunity_detail.html
This PR updates the text for payment import info text to include "Payment Date".
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-795)
=> Update info text to include Payment Date column

commcare_connect/reports/helpers.py
This PR changes the filtering for AVG and MAX time to payment metrics to filter by payment date instead.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-796)
These changes are covered in the automatic tests for this feature.
=> Add AVG and MAX time to payment metrics filter by payment date

commcare_connect/opportunity/tables.py
This is a simple feature request to include phone_number in verification export. (from [slack](https://dimagi.slack.com/archives/C05UNUNH43X/p1741321569585869))
NA
NA
=> include phone_number in an export

commcare_connect/templates/tailwind/header.html, commcare_connect/users/middleware.py
Display the organization name in the navigation bar.
Display the organization role.
[CCCT-878](https://dimagi.atlassian.net/browse/CCCT-878)
[CCCT-878]: https://dimagi.atlassian.net/browse/CCCT-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Top Navigation (org/role)

commcare_connect/opportunity/tw_form_views.py, commcare_connect/opportunity/tw_forms.py, commcare_connect/opportunity/urls.py, commcare_connect/templates/tailwind/pages/form.html, commcare_connect/templates/tailwind/pages/opportunity_edit.html, commcare_connect/templates/tailwind/pages/send_message.html
This PR include
- Opportunity Edit Form
- Add and Edit Payment Unit Form
- Send Message
=> WIP - Forms for Tailwind Conversion

commcare_connect/templates/tailwind/layouts/header.html, commcare_connect/users/middleware.py
This implements the top header menus.
=> Implement header dropdowns

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py
Fixed organization change from PM to NM when PM views opportunities. Updated relevant logic to ensure correct organization context is applied for PM users viewing opportunities.
=> Fixed organization change to PM to NM.

commcare_connect/opportunity/tables.py
Use initial view url for sorting in the worker tables.
=> Use initial view url for sorting

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/views.py
This Pr fixes Last Active and Stated Delivery columns in the worker list table.
Last Active now reflects the most recent form submission date.
=> fixed last active

.gitignore, README.md, deploy/rebuildstaging, requirements/dev.in, requirements/dev.txt
This adds support for being able to build a staging branch to be deployable on staging.
=> Add rebuildstaging support

commcare_connect/program/admin.py
Added Program Applications as inline table on the Program Model.
=> Add program application model to admin

commcare_connect/templates/tailwind/base_table.html, commcare_connect/templates/tailwind/pages/opportunity_worker.html
This PR refactors the pagination component by replacing anchor tags with buttons. JavaScript is utilized to dynamically update and retrieve the most recent URL, addressing an issue where the `querystring` only retains parameters that were originally present in the URL.
Furthermore, the tab functionality has been adjusted to prevent the page parameter from being carried over when the user switches tabs manually.
[QA-7701](https://dimagi.atlassian.net/browse/QA-7701)
Tested Locally
[QA-7701]: https://dimagi.atlassian.net/browse/QA-7701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed Pagination

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/tailwind/pages/invoice_base.html, commcare_connect/templates/tailwind/pages/invoice_list.html, commcare_connect/templates/tailwind/pages/invoice_payment_report.html, config/settings/base.py, tailwind/tailwind.css
Adds invoice/payment pages, along with program-manager and network-manager options to Pay/create-invoices.
=> [New UI] Add invoice/payment page

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/views.py, commcare_connect/templates/tailwind/pages/opportunity_worker.html
This PR ensures that when a program manager exports or imports from the Delivery tab, the review sheet is properly downloaded or imported.
[CCCT-1177](https://dimagi.atlassian.net/browse/CCCT-1177)
Tested locally
[CCCT-1177]: https://dimagi.atlassian.net/browse/CCCT-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [New UI] Download the PM Review sheet

commcare_connect/templates/tailwind/pages/opportunity_worker.html
Added a fix for visit import url not using the correct variable name.
=> Fix Visit Import URL

commcare_connect/opportunity/helpers.py
I have tested the previous query on superset, which took about 2 minutes, I broke this up into subqueries to mirror CTE (CTEs aren't supported in django without django-cte) avoiding previously bigger and complex joins. The optimized one took about 4-5 seconds.
=> [New UI] Optimize worker-deliver query

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/views.py, commcare_connect/templates/form.html, commcare_connect/templates/partial_form.html
This PR adds the "Add Worker" form (Invite User) and some refinements to the form.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1195)
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1202)
=> [New UI] Add Worker Form

commcare_connect/opportunity/views.py
Fixed a bug in Add worker form.
=> Fix remove extra argument from form

commcare_connect/templates/tailwind/components/avatar.html, commcare_connect/templates/tailwind/components/worker_page/profile.html, commcare_connect/templates/tailwind/layouts/header.html, commcare_connect/web/templatetags/avatar.py
Implements initial based avatars
=> [New UI] Avatar using initials

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/models.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py
This Pr addressed these bugs on worker list page.
1. Assessment state should not be failed when learning has not started - [CCCT-1212](https://dimagi.atlassian.net/browse/CCCT-1212)
2. Payment made and payment history do not match. [CCCT-1211](https://dimagi.atlassian.net/browse/CCCT-1211)
3. Combine Date and Time columns in Learn Details Page - [CCCT-1213](https://dimagi.atlassian.net/browse/CCCT-1213)
4. Show count of workers in the Worker List Tab on the Tab Header - [CCCT-1206](https://dimagi.atlassian.net/browse/CCCT-1206)
Tested Locally
[CCCT-1212]: https://dimagi.atlassian.net/browse/CCCT-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCCT-1211]: https://dimagi.atlassian.net/browse/CCCT-1211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> added fix for worker list

commcare_connect/opportunity/views.py, commcare_connect/templates/tailwind/pages/opportunity_dashboard/opportunity_menu.html
This PR fixes the permission for verification flags config menu item and the view redirects non program managers back to opportunity dashboard.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1215)
=> [New UI] FIX Verification Flags Config Permission

commcare_connect/opportunity/views.py, commcare_connect/templates/tailwind/pages/opportunity_dashboard/dashboard.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/opportunity_menu.html
Added Export and Import modal for Catchment Areas.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1194)
=> [New UI] Catchment Area Import Export Forms

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/user_visit_details.html, commcare_connect/templates/opportunity/user_visit_verification.html, commcare_connect/templates/opportunity/user_visit_verification_table.html, tailwind/tailwind.css
This PR adds product teams changes for Worker Visit Verification Page.
- Map Controls
- Disabled Buttons when visits already have that status.
Ticket Links
1. https://dimagi.atlassian.net/browse/CCCT-1244
2. https://dimagi.atlassian.net/browse/CCCT-1243
3. https://dimagi.atlassian.net/browse/CCCT-1245
4. https://dimagi.atlassian.net/browse/CCCT-1271
5. https://dimagi.atlassian.net/browse/CCCT-1269
6. https://dimagi.atlassian.net/browse/CCCT-1270
7. https://dimagi.atlassian.net/browse/CCCT-1259
All changes Tested locally
=> [New UI] Changes for Worker Visit Verification Page

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py, commcare_connect/program/forms.py, commcare_connect/templates/opportunity/add_payment_units.html
Addressed very minor issues in opportunity creation page and opportunity dashboard
https://dimagi.atlassian.net/browse/CCCT-1182
https://dimagi.atlassian.net/browse/CCCT-1246
=> [New UI] Minor Improvements/bug-fixes in opportunity

commcare_connect/templates/opportunity/user_visit_details.html
Added Fix to only show location details when visit has location.
=> Fix only show location details when visit has location

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/views.py, commcare_connect/program/views.py, commcare_connect/templates/opportunity/user_visit_details.html, commcare_connect/templates/program/nm_home.html, commcare_connect/templates/program/pm_home.html, commcare_connect/templates/tailwind/components/cards/user_status_card.html, commcare_connect/templates/tailwind/layouts/sidenav.html, commcare_connect/templates/tailwind/pages/opportunities_list.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/dashboard.html, commcare_connect/templates/tailwind/pages/opportunity_worker.html, tailwind/tailwind.css
Fixed Permission issues for viewer
https://dimagi.atlassian.net/browse/QA-7801
Tested Locally
=> Viewer permission

commcare_connect/templates/tailwind/layouts/sidenav.html
Remove program option for viewers
=> Remove program option for viewers

commcare_connect/opportunity/views.py
This PR addresses an issue that arose after we made some changes to the amount field in payments in #652.
Tested locally and confirmed working. There was an error in the Delivery table, which has now been fixed.
No QA
=> Fixed Decimal conversion issue in payments

commcare_connect/opportunity/admin.py
Resolves [this issue](https://dimagi.sentry.io/issues/6753734229/?project=4505635339829248&query=is%3Aunresolved&referrer=issue-stream) and allows searching by opportunity name in the user invite admin
admin only
=> search by opportunity name

commcare_connect/opportunity/visit_import.py, commcare_connect/templates/opportunity/upload_progress.html
Tested payment and visit import
=> Sanitize test as needed
