config/api_router.py
We can add it later using [accept header versioning](https://www.django-rest-framework.org/api-guide/versioning/#acceptheaderversioning) if needed
=> drop version from API URLs

commcare_connect/templates/base.html, commcare_connect/users/models.py, commcare_connect/users/signals.py
In future we'll probably implement membership management and invitations but for now we just need users to belong to an organization.
=> create organization for user on signup

.env_template, .github/workflows/ci.yml, commcare_connect/cache.py, commcare_connect/commcarehq_provider/views.py, commcare_connect/opportunity/forms.py, commcare_connect/utils/commcarehq_api.py, config/settings/base.py, config/settings/local.py, config/settings/production.py, config/settings/staging.py, requirements/base.in, requirements/base.txt, requirements/dev.txt
* Fetch data in parallel (per domain)
* Cache data to avoid re-fetching when saving the form
In future we may need a 'refresh' button to allow the user to update the app data in case they have made recent changes in CCHQ.
=> performance improvement to fetching app data form CC

.ebextensions/logging.config, config/settings/staging.py
Removed the logging config as this config was running into permission errors on the Elastic Beanstalk EC2 instance whenever Django tried to rotate the logfile.
We can still access the logs as they are captured directly from the stdout by EBS.
=> Remove django logging config for EBS

commcare_connect/opportunity/export.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/tests/test_export.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_detail.html, requirements/base.in, requirements/base.txt
This adds an export button to the opportunity detail view that allows you to download the user visit data as a CSV or Excel file.
The data in the file is the same as shown in the user visit table except with the form data appended to the end. The headers for the form data section are flattened path values e.g. `form.group.1.question`
=> export user visit data including flattened form data

commcare_connect/form_receiver/tests/test_receiver_endpoint.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/form_receiver/views.py
Added OAuth2Authentication and TokenHasReadWrite scope to form receiever api to allow using client credentials.
Connection Settings
=> Add oauth authentication and token permission to form receiver

deploy/README.md, deploy/config/deploy.yml, deploy/inventory.yml
EC2 reboot resulted in a new public IP
=> update ip for new instance

commcare_connect/opportunity/api/views.py, commcare_connect/users/views.py
Usernames in hq are lowercased. This ensures they are stored correctly in the user link model
=> use lowered usernames to match hq

commcare_connect/opportunity/tasks.py
Some users in the db did not have a name previously, this was creating errors when they were added to new opportunities, as the `get` was failing, but `create` violated the unique username constraint. This limits the searching to the unique fields, as well as allowing updates if name or phone number change in connectid.
=> switch to update and move non unique values to defaults

commcare_connect/opportunity/models.py
[Bug Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-134)
- The completed modules queryset did not filter by opportunity and it led a wrong count being shown on opportunity details page learn progress section.
=> Add opportunity filter to completed modules

config/settings/production.py, config/settings/staging.py
This is used by `allauth` in the `build_absolute_uri` and will cause it to use `https` instead of `http`. It looks like the `sites` framework expects the URL to lack a protocol, so I will remove that as well as part of this change.
Right now the constructed URLs begin `http://https://` with `https` coming from the URL in the `Site` object, and `http` coming from `allauth`
=> set default protocol

commcare_connect/opportunity/migrations/0021_deliverunit_remove_uservisit_deliver_form_and_more.py, commcare_connect/opportunity/models.py
FYI @snopoke 
Slugs have a default max length of 50, which was too small for existing values.
=> increase max length

commcare_connect/opportunity/api/views.py, commcare_connect/users/views.py, config/settings/base.py
This pr fixes 2 issues related to repeaters sending data from HQ.
1) HQ doesn't handle refresh tokens correctly for client credentials auth. This sidesteps the issue while I figure out the root cause by extending the length of access tokens.
2) Matching forms to users relies on full usernames, not the short part, which we were not saving.
=> repeater fixes

config/settings/base.py
This setting is supposed to be a number not a string.
=> expiry is number

commcare_connect/opportunity/tasks.py, commcare_connect/templates/opportunity/opportunity_detail.html
[Bug Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-144)
=> Visit import string encode fix

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/api/views.py, commcare_connect/opportunity/tests/test_api_views.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-147)
=> Assesment learn progress api

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tests/factories.py, commcare_connect/opportunity/tests/test_models.py
https://dimagi-dev.atlassian.net/browse/QA-5712
This call wasn't filtering for the user so all users were getting credit for any module submitted.
=> user learn progress

commcare_connect/opportunity/export.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/visit_import.py, commcare_connect/templates/opportunity/opportunity_detail.html
This mostly changes payment import/export to anchor on the username rather than phone number, since that is what most of our other views show, but it also tries to clean up the other tabs in the opportunity details page (removing visit dates and counts from the learn progress table).
=> payment updates

commcare_connect/utils/sms.py
I'm hoping to refactor this to do a dictionary lookup, the same way we do connectid, but it will require adding proper phone number libraries, and this will be fine while we only have one country that requires it.
=> first pass at alphanumeric sender

commcare_connect/opportunity/tables.py, commcare_connect/templates/tables/tabbed_table.html, config/settings/base.py
https://dimagi-dev.atlassian.net/browse/CCPC-161
This should be a fix for the above ticket. It replaces the default pagination controls in the django tables template with custom ones using htmx that take into account our tabbed table setup, by reloading only the relevant table when a pagination control is selected.
This is mostly just copying the pagination block from the [template](https://github.com/jieter/django-tables2/blob/master/django_tables2/templates/django_tables2/bootstrap5.html#L57-L95) we were previously using, and replacing the `<a>` tags with htmx gets that replace the ancestor table element.
=> tabbed table pagination

commcare_connect/opportunity/api/serializers.py
https://dimagi-dev.atlassian.net/browse/QA-5740
https://dimagi-dev.atlassian.net/browse/QA-5737
This updates the deliver API to fix two bugs. It adds the user specific end date and excludes visit that exceeded the daily limit from the progress counts.
=> update deliver api to exclude over limit and add end date

commcare_connect/templates/opportunity/opportunity_list.html
Pagination for opportunity list was not loading due to an incorrect check.
=> Fix opportunity list pagination

commcare_connect/opportunity/visit_import.py
[QA Bug Ticket](https://dimagi-dev.atlassian.net/browse/QA-5741)
Visit Import were failing when the any of the visits had the Over Limit status. The code that converted the visit status converted Over Limit status to "over limit" without the _ in between. This was causing the import to show that some rows have errors. For the fix i have added a replace method to the status_raw string to replace all the spaces with "_".
=> Fix visit import failing on Over Limit status

commcare_connect/templates/base.html
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-136)
- Added a dropdown which shows all the organizations a user is a part of.
- The dropdown on changing organizations redirects the user to the opportunity list page for the selected organization.
=> Add dropdown to switch between different organizations

commcare_connect/opportunity/tables.py
https://dimagi-dev.atlassian.net/browse/QA-5755
There is no way to associate payment units with payments so I am removing that column from the table.
=> remove payment name

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tables.py
This makes the opportunity invite acceptance workflow actually have the intended effect of serving as a consent barrier for personal info. User's who have not accepted will have their names blanked for status until they do. This still allows personal info to bleed through once you submit delivery forms, but since that point is when payment gets involved as well as manual verification of work, that seems necessary.
=> hide name until accepted

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tests/test_forms.py, commcare_connect/templates/opportunity/opportunity_create.html, commcare_connect/users/views.py
The two commits in this PR address two issues
1) As seen in the screenshot below, it adds a new field of "max users" and automatically calculates the total budget so users do not need a calculator. It does not change anything on the backend, and we still only store the total budget.
2) Marks an opportunity as accepted when the user starts learning. This aligns with common sense understandings of what it means to accept an opportunity, and will be reflected in new language in the mobile UI indicating that starting learning consents to sharing the user info (in this case just name) with the project.
=> budget updates

commcare_connect/opportunity/forms.py
It turns out disabled fields are not submitted on form submission. This arguably makes the UI a little worse, but keeps the form data, and is still clear that field is not editable.
=> switch to readonly

commcare_connect/users/helpers.py
Create HQ User currently does not log anything when the api request return any status other than 201.
This PR adds logging to the function in case the api return an error.
=> Add logging to create hq user

commcare_connect/opportunity/api/views.py
This PR fixes the test for Claim API endpoint failing only sometimes causing PR to show a test failure which goes away on subsequent runs. 
This test requests the Claim API endpoint twice to validate that the `Opportunity is Already Claimed` error status is returned. In this case the test status that came back were randomized as the Opportunity Factory sometimes assigns budget which is smaller that the budget required for the max_payments which are claimed by a User and it led to a different status to be returned leading to test failure.
=> Fix randomly failing test for Claim API Endpoint

commcare_connect/opportunity/api/views.py, commcare_connect/opportunity/tests/test_api_views.py
This fixes 2 bugs in the claim workflows
1) The claim logic was mixing up budgetary limits and visit limits so this fixes that comparison to only use the same units (visits/payments in this case).
2) The API was returning 200 even when the claim failed so mobile assumed it succeeded. These now return 400
=> return 400 for bad claim and update max_payment logic

commcare_connect/utils/commcarehq_api.py
This times out when users have a domain with many apps. This is a temporary workaround, but at least makes sure the opportunity creation page is unlikely to fail.
=> extend app fetch timeout

commcare_connect/opportunity/api/serializers.py
Mobile currently chokes on null data. This ensures non null data is always sent for these fields. We can revisit the long term state of these chagnes when the mobile deserialization code is updated.
=> add defaults to avoid sending nulls

deploy/config/deploy.production.yml
This limits the celery docker container to half the memory of the machine, to prevent the OOMs from large exports.
=> limit celery memory

commcare_connect/opportunity/views.py
This PR fixes two bugs in Opportuntiy Add budget to exisiting users workflow.
1. Additional visits assigned to users were not added to the total budget for the opportunity
2. When no end date was selected by users the end_date was unbound and led to an error.
=> Fix additional visits save to opportunity total budget

commcare_connect/conftest.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/opportunity/tests/test_api_views.py, commcare_connect/users/tests/factories.py
This PR adds tests for all the apis which are in the Opportunity django project. Also removed unused factories and fixtures.
=> Opportunity APIs Tests

commcare_connect/form_receiver/tests/test_receiver_integration.py
Fixes broken Form Receiver test after the Opportunity API Tests PR was merged. Form Receiver test updates opportunity claim to check if the API assignes correct status to received forms.
=> Fix receiver test update opportunity claim

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/tables.py
It was making a row for every value of `passed_assessment`, this aggregates all values into 1 by summing. If any assessment has value 1 (meaning it is for the right opportunity and is passed), they will get a true value, otherwise a failing value.
=> sum assessments and skip total

commcare_connect/opportunity/export.py, commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/tests/test_export.py
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-217)
This PR includes fixes for bugs related to the User Status Table.
- Exports through excel were failing due to date with timezone info, this bug is fixed now and the timestamp are converted to naive date time timestamps.
- The date for Completed learn was not showing up for users due to incorrect completed_modules_count being calculated as the `distinct=True` param was not specified for the Count function.
- Fixed the User Status Table not loading up due to None opportunity claims for users who have not yet claimed the opportunity, which also caused the total column to error.
=> Fix user status table export aggregates queries

commcare_connect/opportunity/tests/test_api_views.py
This test was failing intermittently because the validation status was being set to `over_limit` which is not returned by the API.
=> set validation status

commcare_connect/opportunity/views.py
This page is currently ordered in ascending order (those who have accrued the least payment first). This reverses the ordering so the most active users appear first instead of last.
=> descending order by payment

commcare_connect/users/helpers.py
This solves two related problems that blocked some users for the additional opportunities.
First, the change to `httpx` in https://github.com/dimagi/commcare-connect/pull/196/files created a very short timeout (5 seconds) for the create user call. This lengthens in a but to try to prevent httpx from giving up on the call, something that can still result in the user being created on HQ, but now without connect knowing.
Second, instead of erroring when the user is already created, it allows the function to continue. That way the connect user will be linked to the already created hq user, rather than being permanently blocked. Connect only calls this API if it does not already have a record of creating the user, so as far as I know, the main way we get into this state is the first problem …
=> user already created

deploy/production.inventory.yml
This will stop all of our sentry issues from saying they are in the `staging` env, and does a minor refactor of ansible variables
=> reorganize vars and add sentry env

commcare_connect/opportunity/models.py
[Sentry error](https://dimagi.sentry.io/issues/4619727337/?environment=staging&project=4505635339829248&query=&referrer=issue-stream&statsPeriod=90d&stream_index=1&utc=true)
There was a zero division error due to some opportunities not having learn modules. The learn modules are used to calculate the learn progress percentage for a user and 0 learn modules led to zero division error in that calculation.
As a fix that calculation checks if the learn modules count is 0 and returns 0 early.
=> Fix zero divison error

commcare_connect/opportunity/export.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/views.py, commcare_connect/templates/export_modal.html, commcare_connect/templates/opportunity/opportunity_detail.html
There was a lot of duplication of code around the export code for payment export, user status export and deliver status export.
- This PR includes a export_modal template which can be used for exporting data in future.
- Refactored the code to use the save_export helper function
=> Refactor Export Code

commcare_connect/organization/forms.py, commcare_connect/organization/views.py
Added a filter to the add member dropdown on organization page to exclude all mobile users and show only the web users that are not already invited to the organization.
=> Add filtering for web users on add members

config/settings/base.py
The admin page for SocialAccount and SocialToken models from all auth is broken for Connect because they cannot resolve the user display string correctly. 
This PR adds the `ACCOUNT_USER_DISPLAY` config variable with the `str` callable to resolve the user display using the `user.__str__` method.
=> Fix broken all auth admin

commcare_connect/opportunity/app_xml.py
this was causing some issues where deliver units were not appearing in an opportunity 
https://dimagi.sentry.io/issues/4605106604/?project=4505635339829248&query=is%3Aunresolved+create_learn_modules&referrer=issue-stream&statsPeriod=90d&stream_index=0
=> increase tiemout for fetching app structure

commcare_connect/opportunity/admin.py
This lets admins refresh deliver units and learn modules in an opportunity. Use at your own risk
=> refresh apps in opp admin

commcare_connect/opportunity/admin.py
This creates an admin action in the OpportunityAccess admin to reset the progress of a user, deleting all existing submissions from them. This is not to be used in live opportunities but we can start testing it in the demo practice ones, while we refine its behavior.
=> admin action to clear user progress

commcare_connect/opportunity/forms.py, commcare_connect/static/js/htmx.js, commcare_connect/static/js/vendors.js, commcare_connect/templates/base.html
[Ticket](https://dimagi.atlassian.net/jira/software/c/projects/CCCT/issues/CCCT-235)
This PR fixes 
- the htmx loading-states plugin which was not working correctly as it cannot find the htmx library.
- The disabled states for the Learn and Deliver app dropdown when fetching domain
- Added a small delay 0.3s to let htmx disable the elements before requesting the Applications.
=> Fix broken loading states for learn, deliver dropdowns

commcare_connect/form_receiver/serializers.py
The form processor serializer was throwing validation errors for forms that had a null location field. This PR adds the allow_null param for the serializer location field.
=> Fix location allow null form processor

commcare_connect/static/js/vendors.js
The org dropdown which is a bootstrap component was broken due to duplicate import for bootstrap javascript.
=> Fix broken org dropdown

commcare_connect/form_receiver/processor.py
Add the same location flag only on the form submissions for the same delivery unit. This fixes the bug around flagging duplicates for multi-visit interventions.
=> Fix flag location on same deliver units

commcare_connect/opportunity/tables.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-259)
- The last footer column in the User Status Table shows the total users invited to the opportunity i.e the total number of rows in the UserStatusTable.
=> Add total invited users count to User Status table

commcare_connect/templates/opportunity/send_message.html
[Ticket](https://dimagi.atlassian.net/browse/QA-6131)
- Fixes the send message table styling for table header to make it similar to other tables.
=> Fix send_message table styling

config/settings/base.py
This PR removes the recurring Django `Disallowed Host` errors from Django logs and sentry.
=> Fix remove django allowed hosts errors from logs

commcare_connect/opportunity/export.py
Since attachment ids are the keys of a sub dictionary, when we flatten form data we add four columns to the  for every attachment (ie if 4 forms have `attachments` we add 16 columns). The attachment data isn't particularly useful and this should shrink the export a fair amount.
=> do not include attachment data in export

commcare_connect/opportunity/api/serializers.py
The pk is needed so the mobile can identify the payment being confirmed.
=> add payment pk

config/settings/base.py
This adds basic settings to allow API versioning with our django rest framework views. We will need to do a custom subclass of the versioning class, but for now this gives mobile something to play with.
=> Add API versioning settings

commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/opportunity/models.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/visit_import.py
The payment accrued calculation does not calculate the payment correctly when an approved completed work is rejected.
Also combined the similar `update_payment_accrued` and `approve_completed_work_and_update_payment_accrued` function.s
=> Fix payment accrued

commcare_connect/opportunity/api/serializers.py
[Ticket](https://dimagi.atlassian.net/browse/CCCT-300)
Changes:
- Opportunity List API now includes a new key `payment_units` which is an array of payment units for the opportunity.
```
payment_units: [
{
id: 1,
name: "Payment Unit 1",
total_max: 100,
daily_max: 2
}
]
```
- Opportunity List API `claim` key updated to include information from different payment unit configurations for the user.
- Note: the `payment_unit` key below is the payment_unit id.
```json
"claim": {
"max_payments": 200,
"end_date": "2024-05-06",
"date_claimed": "2024-04-12",
"payment_units": [
{
"max_visits": 100,
"payment_unit": 1
},
{
"max_visits": 100,
"payment_unit": 2
}
]
}
```
=> Multi Visit API changes to Opportunity List API.

commcare_connect/opportunity/views.py, commcare_connect/templates/opportunity/opportunity_list.html, commcare_connect/web/templatetags/sort_link.py
https://dimagi.atlassian.net/browse/CCCT-267
=> Display start/enddate and make sortable table

commcare_connect/opportunity/models.py
I will add tests to this in a followup PR, but this makes sure that if a dependent payment unit has been rejected, the auto approval will not cause payment to be accrued. Previously, since the child unit showed as completed, even when it was rejected, the parent would be approved and money would accrue.
I am not positive this is the best place to fix this behavior (rather than not approving the payment unit itself), but it seemed like a reasonable option. Open to the idea of moving it to the approval code and rejecting the payment unit in that instance instead.
=> only count approved child payment units

commcare_connect/opportunity/export.py, commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_export.py, commcare_connect/opportunity/views.py
This is a temporary fix for the export issues we are facing in production. That is primarily caused by the exceptionally wide tables being generated from flattening form data. This creates a toggle, defaulting to leaving the data in a single column as json but keeping the option to have a wide table. I am not sure this is a great solution, but should at least let projects start to get data out.
=> add option to not flatten export

commcare_connect/opportunity/forms.py
If boolean fields are not marked with `required=False`, form validation fails when it is unchecked. I find this completely nonsensical and mildly infuriating, but such is life.
[Docs](https://docs.djangoproject.com/en/5.0/ref/forms/fields/#booleanfield)
=> toggle is not required

commcare_connect/opportunity/api/serializers.py
We need to order by the PK of the payment unit, not the user's claim on that unit
=> order by payment unit id

commcare_connect/opportunity/export.py
The form data was being included in the string representation of a python dictionary, rather than json, which prevented using excel JSON functions.
=> dump form dict as json

commcare_connect/opportunity/api/serializers.py
Previous attempts covered other APIs, but this one was missed.
=> order payment units in opportunity api

commcare_connect/users/views.py
This PR adds a change to accept the UserInvite when the user starts a learn app. This was missing in the User Invite PR.
=> Fix update user invite status on start learn app

commcare_connect/reports/tables.py, commcare_connect/reports/views.py
In the admin reports, we need to break up the payment amounts by currency (it doesnt make sense to add 1000 kwacha to 1000 rupees). This sums them separately and displays them together, one per line, in the same cell.
=> currency display

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tables.py
I added the amount of confirmed payment to the payment status table that shows up in the main opportunity info page so it was easy to compare confirmed payments to claimed payments.
=> add confirmed payments to payment table

commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_tasks.py
This PR changes the Notification Payload structure to support notification in background and app killed states.
I have deployed this PR on staging and tested this change with help from the mobile team and the notification are working now in all app states i.e background, foreground and killed.
See comments on this ticket for more info. https://dimagi.atlassian.net/browse/CCCT-77
=> Update notification data for background notifications

commcare_connect/reports/tables.py, commcare_connect/reports/views.py
This fixes a couple bugs in the admin report.
1) The `render_X` functions were not updated for new payment column names
2) Quarter start and end dates were wrong. Quarter Q starts on month (Q - 1) * 3 + 1. For example,
Q1 starts on (1 - 1)*3 +1=1
Q2 starts on (2 - 1)*3 +1=4
=> update quarter date calculation

docker/start, docker/start_migrate
Gunicorn was killing requests taking longer than 30 seconds, this gives us a little breathing room for long requests like the admin reports
=> increase gunicorn timeout

commcare_connect/opportunity/models.py
[QA-Ticket](https://dimagi.atlassian.net/browse/QA-7068)
This bug was recently found in QA. The code throws a unique key error because it tries to create an already-created Claim Limit configuration due to the `max_visits` filter in `get_or_create`. The `max_visits` are only required when a new ClaimLimit is created, so moving it to the `defaults` parameter of `get_or_create` avoids the unique key error and adds `max_visits` specified to any new claim limits that are created.
=> Fix claim limit unique key error due to max_visits

docker/start, docker/start_migrate
We currently run gunicorn with a single worker and a single thread, which means all requests are handled sequentially. This changes our setup to run two gunicorn processes, each using gevent to service multiple requests concurrently.
=> Use gevent workers

commcare_connect/opportunity/utils/completed_work.py
This and #399 have been due to a merge issue for the changes of the Program Management feature recently deployed to production. The PR that this change was a part of was based on an older version of changes on the main that caused the status updation code to get out of sync with branch and later during merge this caused issues when the code was finally adjusted to the latest changes.
=> Fix review_status missing from query

commcare_connect/templates/base.html
I realize we're probably not expecting random people to land on this site, but it still seems better to have something basic in place at https://connect.dimagi.com
=> change the default landing page content

commcare_connect/reports/management/commands/generate_test_data.py, commcare_connect/reports/sql/visit_map.sql, commcare_connect/reports/sql/visit_map_superset.sql, commcare_connect/reports/urls.py, commcare_connect/reports/views.py, commcare_connect/templates/reports/dashboard.html
[Context / Working Spec Here](https://docs.google.com/document/d/19Ds59vZ7PHRcNIEFjOoIQBIJSZ3r8t9idR-wZdr-SkM/edit)
This PR has a few pieces that I used to make a little map PoC in the dashboard:
1. A test data generator that generates random visits.
2. A SQL query (based on the one used in superset) to format the map data.
3. A view to show the data on a map.
This is the end result:
[connect-map-poc.webm](https://github.com/user-attachments/assets/f50cf336-34fa-4895-b145-1fab460c56c8)
Of course the data looks ridiculous when randomly generated, which is one reason it would be nice to have this deployed to the real app.
=> Dashboard Maps PoC

commcare_connect/form_receiver/processor.py, commcare_connect/form_receiver/tests/test_receiver_integration.py
This was crashing when a form with no location was submitted by a user with assigned catchment areas. I think it's a bit debatable whether we should include the flag in that case, but I like that it signals to the reviewer that the user did have an assigned area. One that we are not sure if they were inside.
=> handle empty location with catchment areas

commcare_connect/conftest.py, commcare_connect/opportunity/tests/factories.py, commcare_connect/reports/tables.py, commcare_connect/reports/tests/test_reports.py, commcare_connect/reports/urls.py, commcare_connect/reports/views.py, commcare_connect/templates/reports/htmx_table.html, commcare_connect/templates/reports/report_table.html, config/settings/base.py, requirements/base.in, requirements/base.txt
- Refactor to htmx based reports
- Add filters
=> add delivery-type, year, quarter filter to admin report

commcare_connect/templates/opportunity/opportunity_detail.html
This PR fixes a bug in conditions that hide the links to Review User Visits and Invoices page for Network Manager users.
=> Fix allow PM and NM to view review users visits and payment invoices pages

commcare_connect/templates/opportunity/invoice_list.html
Fixed translate tag not working in the invoice list template due to missing initialization for internationalization tags.
=> Fix Invoice List Internationalization

commcare_connect/reports/tests/test_reports.py, commcare_connect/reports/views.py
https://dimagi.sentry.io/issues/5969364576/
=> fix bad data in admin map api

commcare_connect/opportunity/export.py
I think this should fix the flaky test (and make sure that visit exports are always in the same order, which might be nice anyway).
=> adding consistent ordering to visit export

commcare_connect/opportunity/migrations/0060_completedwork_payment_date.py, commcare_connect/opportunity/utils/completed_work.py
This PR updates the `update_work_payment_date` function to dynamically assign model references `(Payment and CompletedWork)` within the function. This change ensures compatibility with Django's migration system, where historical models must be used.
By avoiding top-level imports, the function can now:
Use historical models when called from migrations (via `apps.get_model()`).
Fallback to current models when called during normal app execution.
This approach prevents issues caused by schema changes between migration and runtime models, ensuring smoother migrations and consistent behaviour.
For reference- [Historical-models](https://docs.djangoproject.com/en/5.1/topics/migrations/#historical-models)
=> Fix for historical model issue in opportunity 0060 migration.

commcare_connect/conftest.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/tests/factories.py, commcare_connect/opportunity/tests/test_api_views.py
This adds form submission end/start flags into Opportunity API
=> include submission time slot in opportunity API

commcare_connect/conftest.py, commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/opportunity/tests/factories.py, commcare_connect/opportunity/tests/test_views.py, commcare_connect/opportunity/tests/test_visit_import.py, commcare_connect/opportunity/views.py, commcare_connect/reports/tests/test_reports.py
This PR adds missing tests for the Enterprise User Visit Review functionality in the Program Management features.
=> Program Management Tests

commcare_connect/opportunity/views.py
Implemented the changes that were requested in a previous pull request, which has already been merged (see [discussion](https://github.com/dimagi/commcare-connect/pull/379#discussion_r1755959139))
=> Opportunity views improvements.

commcare_connect/conftest.py, commcare_connect/form_receiver/tests/test_receiver_integration.py
This PR adds a managed opportunity return to the opportunity fixture.
=> Add ManagedOpportunity return to Fixture

commcare_connect/opportunity/admin.py
This allows searching the django admin for opportunity access by username (basically get a list of all opportunities that a user is a member of).
=> allow search by username

commcare_connect/organization/forms.py, commcare_connect/organization/tests/test_forms.py
[CCCT-525](https://dimagi.atlassian.net/browse/CCCT-525)
[CCCT-525]: https://dimagi.atlassian.net/browse/CCCT-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Modified the organization member invite flow by replacing the current email selection dropdown with a text field to allow direct entry of user email addresses
=> Update Organization Member Invite Flow to Use Text Field

commcare_connect/static/js/project.js, commcare_connect/templates/opportunity/user_profile.html
[CCCT-561](https://dimagi.atlassian.net/browse/CCCT-561)
[CCCT-561]: https://dimagi.atlassian.net/browse/CCCT-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> User profile changes

commcare_connect/users/helpers.py
This error surfaced recently when QA tried to reopen an opportunity and invite some users. These were already created on HQ. The request returns "Username {} is already taken or reserved" and we are checking for "already exists" in the response text which caused the check for an already existing user to be skipped and raised the API exception.
[Sentry Error Link](https://dimagi.sentry.io/issues/4620204019/?environment=staging&project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true)
=> Fix text check causing issues in hq user creation

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py
[Slack message](https://dimagi.slack.com/archives/C05UNUNH43X/p1732863342736529)
When the Program Manager (PM) tries to view the visit, the system incorrectly picks the organization slug from the opportunity. This is problematic in the case of a managed opportunity because, when the PM views the opportunity, the verification process checks whether the user belongs to that organization. However, it is not necessary for a user belonging to the PM organization to also belong to the NM organization. This fix addresses that issue.
=> Added the org slug in table

commcare_connect/form_receiver/processor.py
Should fix https://dimagi.sentry.io/issues/6098769063/?project=4505635339829248&referrer=slack [introduced here](https://github.com/dimagi/commcare-connect/pull/421/files)
=> Check for None value

commcare_connect/opportunity/management/commands/delete_duplicate_visits.py, commcare_connect/opportunity/tests/test_commands.py
[CCCT-571](https://dimagi.atlassian.net/browse/CCCT-571)
[CCCT-572](https://dimagi.atlassian.net/browse/CCCT-572)
Added a command to delete duplicate visits that were created when the same forms were re-forwarded from HQ.
[CCCT-571]: https://dimagi.atlassian.net/browse/CCCT-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCCT-572]: https://dimagi.atlassian.net/browse/CCCT-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Command to delete duplicate visits

commcare_connect/opportunity/management/commands/auto_approval_opportunities.py
This maintains default behavior but allows the option to also process over limit `CompletedWork`, necessary for some data correction.
=> add option to include over limit works

commcare_connect/opportunity/views.py
The Approve Visit view allows the review to be created for already approved forms. This PR checks if the status is approved and skips creating the review for those forms.
This is partly related to this [ticket](https://dimagi.atlassian.net/browse/CCCT-578).
=> Fix Review creation for Already Approved Visits.

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tests/test_api_views.py, commcare_connect/opportunity/tests/test_models.py
The remaining budget calculation for Managed Opportunities was off due to the org_pay component added to the total budget. To calculate the effective user total budget we have to remove the org_pay component from the total budget, then this user total budget can be used to calculate the remaining budget.
This PR will fix the remaining budget calculation and also fix the bug related to Opportunity Claims getting created for users in opportunities where the budget is exhausted.
[Ticket](https://dimagi.atlassian.net/browse/CCCT-562)
=> Claim Limit Remaining Budget Fix

commcare_connect/opportunity/visit_import.py
[CCCT-549](https://dimagi.atlassian.net/browse/CCCT-549)
[Sentry link](https://dimagi.sentry.io/issues/6059769484/?environment=production&project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=7d&stream_index=11)
- The deadlock error indicates that two separate transactions were trying to access the same data in conflicting orders, even though the code is using a single transaction.atomic() block.
- This suggests there are concurrency issues beyond just the single transaction, likely due to the fact that this is a Celery task.
- The` transaction.atomic()` block only ensures atomicity within a single Celery task, but does not prevent deadlocks between multiple concurrent tasks.
To resolve this, I have used cache …
=>  Deadlock Detected in bulk update payments.

commcare_connect/opportunity/tests/factories.py
This PR fixes the unique key violation error that randomly occurs in the CI test runner. Using the [django_get_or_create](https://factoryboy.readthedocs.io/en/stable/orms.html#factory.django.DjangoOptions.django_get_or_create) meta option for OpportunityAccessFactory, we can specify to run the `get_or_create` method to create objects when certain fields are present, in this case, `user` and `opportunity`. This will help avoid creating duplicate OpportunityAccess for users.
[Failing CI Run and Test Description](https://github.com/dimagi/commcare-connect/actions/runs/12312178249/job/34363704785)
=> Fix unique key violation error in tests

commcare_connect/program/helpers.py, commcare_connect/program/tables.py, commcare_connect/program/tests/test_helpers.py
[CCCT-570](https://dimagi.atlassian.net/browse/CCCT-570)
[CCCT-585](https://dimagi.atlassian.net/browse/CCCT-585)
[CCCT-570]: https://dimagi.atlassian.net/browse/CCCT-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CCCT-585]: https://dimagi.atlassian.net/browse/CCCT-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Negative average time to convert in funnel performance report.

commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py
This PR fixes when the delete button is shown for User Invites. Currently, the button was shown for all invites that were not accepted, but it needs to be shown only in cases when a user was not found in ConnectID.
I have tested these changes on staging.
=> Fix invite delete conditions

commcare_connect/utils/middleware.py, config/settings/base.py
This should make it easy to trace 500s when users report issues.
=> capture user/org tags in sentry

commcare_connect/opportunity/visit_import.py
We already returned the "rates" key from the response on line 301, so we can directly look up the currency code here. I also added some error checking to make sure we don't create null rates.
=> fix exchange rate fetch

commcare_connect/utils/middleware.py, config/settings/base.py
Reverts dimagi/commcare-connect#449
This was setup incorrectly, causing all requests to 500 https://dimagi.sentry.io/issues/6226579176/?alert_rule_id=14580978&alert_timestamp=1737145963323&alert_type=email&environment=production&notification_uuid=6806dcb1-39f4-4627-9651-8352570c3383&project=4505635339829248&referrer=alert_email
=> Revert "capture user/org tags in sentry"

commcare_connect/opportunity/visit_import.py
This fixes an error when the user tries to submit payments with non-integer amounts i.e INR 1000, USD 100.
This error was due to the Unbound amount variable when the ValueError exception occurred for non-integer amounts.
[Sentry Link](https://dimagi.sentry.io/issues/6248248829/?alert_rule_id=14580978&alert_timestamp=1737889101584&alert_type=email&environment=production&notification_uuid=2f06f11a-7b8c-4640-83a9-c2f79eb3bf64&project=4505635339829248&referrer=alert_email)
=> Fix UnboundLocalError when accessing amount

commcare_connect/reports/views.py
I believe I misinterpreted the data included in these payments, and the behavior was correct before (we are just behind on some org payments which is why the number was lower than FLW payments).
=> Revert "include totals for orgs"

commcare_connect/opportunity/tables.py
This PR adds filters and sortable fields for the User Visit Review page.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-577)
The features included in this PR are deployed and tested on staging.
None
None
=> User Visit Review Page: Filters and Sortable fields

deploy/roles/connect/templates/docker.env.j2
This is the correct name of the env variable referenced in the [new settings](https://github.com/dimagi/commcare-connect/pull/481/files#diff-f7a16228131ae92457c22657bb33458207a7578b8cdb6ff796153916fa67a22dR49)
=> change env variable name

commcare_connect/reports/helpers.py, commcare_connect/reports/tests/test_reports.py
This fixes the negative average time to payment dates generated due to invalid payment dates set for completed work records that are in the past.
[Ticket](https://dimagi.atlassian.net/browse/CCCT-769)
Already Covered in test included earlier.
=> Fix filter only valid payment dates

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/visit_import.py, commcare_connect/program/forms.py
Currently, when the currency code "USD" is in lowercase, the system incorrectly attempts to fetch the rate from the rates API. This update ensures that currency code comparisons are case-insensitive by converting currency_code to uppercase before checking against "USD", preventing unnecessary API calls due to case mismatches.
[Sentry Error](https://dimagi.sentry.io/issues/6289210916/?project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=24h&stream_index=2)
=> Ensure Case-Insensitive Currency Code Comparison

docker/start, docker/start_migrate
We are still seeing frequent unreachable docker containers but there is no evidence the containers themselves are going down, which leads me to believe the workers are being saturated. This adds extra workers while still staying (mostly) within gunicorn recommendations.
=> have ten gunicorn workers

commcare_connect/program/admin.py
Currently, it is not straightforward to determine the PM's organisation from the program name in the NM view of our UI. Adding the Program model to the Django admin will make it easier for admins to access and manage program details, including their associated organisations, directly from the admin panel.
=> Add Program Model to Django Admin

commcare_connect/reports/helpers.py, commcare_connect/reports/tables.py, commcare_connect/reports/tests/test_reports.py, commcare_connect/reports/views.py, commcare_connect/static/js/vendors.js, commcare_connect/templates/base.html, commcare_connect/templates/reports/report_table.html, commcare_connect/utils/datetime.py, package-lock.json, package.json
This PR removes the year and month filters and adds support for filtering using custom date ranges.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-779)
This PR also adds refactors for the way grouping in queryset works.
- Tested on staging
- Added test to cover the new changes.
=> Add Date Range filtering to Dashboard

commcare_connect/form_receiver/processor.py
We have been seeing a high volume of UserVisit.DoesNotExist errors on [Sentry](https://dimagi.sentry.io/issues/6302069322/?project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=0)
This PR ensures that `download_user_visit_attachments.delay(user_visit.id)` is only triggered after the transaction is successfully committed using `transaction.on_commit()`. This guarantees that the Celery task only runs once the `UserVisit` record is available in the database.
This change does not alter any data or logic beyond ensuring the function is called at the right time.
=> Ensure the Transaction is Committed Before Celery Runs download_user_visit_attachments.

commcare_connect/opportunity/forms.py
This fixes an error in the OpportunityChangeForm code related to end_date setter. In the new Opportunity creation flow, when the opportunity is only partially setup, the end date field is None, this adds checks for existence of a valid instance and a valid end_date before setting them in the OpportunityChangeForm.
[Sentry Link](https://dimagi.sentry.io/issues/5168594132/?environment=production&project=4505635339829248&query=is%3Aunresolved%20isoformat&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=0)
=> Fix check if instance and end_date exists

commcare_connect/opportunity/admin.py
This adds a tabular inline for User Visits on the completed work admin page to show related user visits. This makes it easier to debug issues.
=> Add tabular inline for UserVisits on completed work

commcare_connect/opportunity/tests/test_views.py, commcare_connect/opportunity/tests/test_visit_import.py, commcare_connect/opportunity/views.py, commcare_connect/opportunity/visit_import.py, commcare_connect/templates/opportunity/opportunity_detail.html, commcare_connect/templates/opportunity/visit_verification.html
Added mandatory justification for flagged visits in managed opportunity cases. This applies both when manually approving visits and when importing visits via file [CCCT-836.](https://dimagi.atlassian.net/browse/CCCT-836)
Tested locally
Existing tests are passing. Added new test cases for different scenarios.
=> Make 'Justification' field mandatory for NMs

commcare_connect/templates/opportunity/opportunity_detail.html
This PR fixes the if condition, as `export/import PM review visit options` are visible on normal opportunities as well.
Only the if condition was changed, so the update is low risk.
=> Fix for Export/Import PM Review Visit Being Visible on Normal Opportunities

commcare_connect/reports/helpers.py, commcare_connect/reports/tests/test_reports.py
This PR Fixes
- Total Eligible User and Total ConnectID Accounts cumulative counts
- Added Fixed windows for calculating cumulative counts and using those in queries
- Fixed Eligible User Count queryset filtering
- Removed filters related to payment data in user counts filtering
- Moved these filters to the time to payment data queryset     
- Automated tests cover these changes.
=> Fix Total Eligible Users and Total ConnectID Counts

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/tests/test_api_views.py
[CCCT-660](https://dimagi.atlassian.net/browse/CCCT-660)
Added unique `id` fields in REST API responses to ensure distinct identity for data.
Updated existing tests to verify the presence of the id field.
NA
[CCCT-660]: https://dimagi.atlassian.net/browse/CCCT-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add pk in rest api calls 

commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_visit_import.py, commcare_connect/opportunity/visit_import.py
Added a celery task for the update_payment_accrued function for bulk imports. The update_payment_accrued task times out in a web worker. Doing this task in a celery task will let the import process go without timing out, and the payment accrual can happen asynchronously independent of the upload.
Payment accrual code performance is very bad due to multiple queries made during the `approved_count` and `completed_count` calculations for CompletedWork. A better solution would be to improve those functions but to unblock the users right now, we have to settle for an intermediate solution while we figure out how to improve that calculation.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-870)
- This code involves turning a well-tested function into a task.
=> Async update_payment_accrued for Imports

commcare_connect/opportunity/models.py, commcare_connect/opportunity/tests/test_models.py
We are having an issue with the `completed` count, as it takes too long when the number of visits is large. Instead of calculating it in real-time, using the `saved_completed_count` to track the visits.
[Slack thread](https://dimagi.slack.com/archives/C05UNUNH43X/p1742896758996559)
[Sentry Error](https://dimagi.sentry.io/issues/6456670514/?project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=0)
Updated the test so that saved_completed_count is updated.
Rest all test are passing.
=> Used saved completed count to count visit count.

commcare_connect/form_receiver/processor.py, commcare_connect/opportunity/forms.py, commcare_connect/opportunity/urls.py, commcare_connect/opportunity/views.py
This PR prevents a 500 error when the payment unit is null in the delivery unit, which happens when the deliver unit is created later or not configured with a payment unit. Since OpportunityClaimLimit requires a payment unit, this issue needs to be handled properly.
Key Updates:
- Sync Deliver Units from HQ: Added an option in the "Add Payment Unit" form to sync deliver units from HQ, allowing users to assign a payment unit to newly added deliver unit.
- Improved Error Handling: The form processor now returns a clear error message instead of failing with a 500 error.
[CCCT-898](https://dimagi.atlassian.net/browse/CCCT-898)
https://github.com/user-attachments/assets/fd4936e8-8343-47fb-9264-691b434067d8
Most of the code relies on existing functions that have been working correctly. The …
=> Handle Missing Payment Unit in Deliver Unit

commcare_connect/templates/base.html
This PR updates the display condition for the Program button on the navbar. Previously, superusers could see the button even if the organization was not marked as a Program Manager. Now, visibility requires the organization to be a Program Manager, regardless of superuser status.
This is a low-risk change. Only a simple condition was updated, and it has been tested locally to confirm correct behavior.
=> Only show program option when flag is set to true

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/tests/test_api_views.py
This PR introduces the end_date field in the Payment Unit serializer to ensure mobile clients receive this information.
[CCCT-910](https://dimagi.atlassian.net/browse/CCCT-910)
This is a low-risk change, as it only involves adding an additional field to the serializer.
Tests have been updated to account for the new field, and all tests pass successfully.
NA
[CCCT-910]: https://dimagi.atlassian.net/browse/CCCT-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add payment unit end_date to mobile api

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/tests/test_api_views.py
No user-facing changes, only API data update.
[Ticket](https://dimagi.atlassian.net/browse/CCCT-654)
This PR makes sure to serialize the CompletedWork records' flags as part of the CompletedWorkSerializer in a dictionary style with slug as key and description as value. For example, the jsonified response would look like this:
```
{
...
"deliveries": [
{
...
"flags": {
"duration": "The form was completed too quickly."
}
}
]
}
```
The `test_delivery_progress_endpoint` test [asserts](https://github.com/dimagi/commcare-connect/blob/f69702d46963576eaf19c020a855e3f2d7996f8d/commcare_connect/opportunity/tests/test_api_views.py#L238) that the serialized delivery keys be similar to the `UserVisitSerializer`, but that's not the correct serializer class that's being used in the …
=> Serialize CompletedWork flags in CompletedWorkSerializer

commcare_connect/opportunity/forms.py, commcare_connect/program/tests/test_forms.py
This PR handles an erroneous situation more gracefully.
[Sentry issue](https://dimagi.sentry.io/issues/6536627294/?project=4505635339829248&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=5)
An issue was found on sentry where the `learn_app` was not apparently set in the form, despite the field being required.
I'm not 100% sure how to replicate this from the UI as it seems theoretically impossible (as least as a user), but I've managed to replicate it using a unit test.
The solution might work to stop the sentry issue, but I'm curious to know why and how it happened in the first place. Also curious why we have an explicit check for `cleaned_data` in the `clean` method, since data should always be present? 
Added a unit test
No …
=> Gracefully handle missing form field

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/views.py
This PR adds a default order to the opportunity list. The list will now be ordered by `status`, `start_date`, and `end_date` by default.
Additionally, it updates the list to include opportunities managed by an organization through a program.
=> added opportunity order

commcare_connect/reports/views.py
No user facing changes.
This just converts the stats view for the admin dashboard to a DRF view so that it can be more easily used by external APIs. I'm using this for a proof-of-concept demo of an MCP integration.
There are no user facing changes, I tested this locally, and everything works as expected.
=> make the dashboard stats an API view

commcare_connect/opportunity/api/serializers.py, commcare_connect/opportunity/visit_import.py
No user-facing changes.
Relevant Slack discussion thread [here](https://dimagi.slack.com/archives/C05APTXCTSM/p1746453947390889?thread_ts=1746430482.305919&cid=C05APTXCTSM).
This PR resolves an issue where the `send_delivery` endpoint would sometimes serialize an `OpportunityAccess` instance and send a "null" string for the `reason` field in the JSON data. A likely cause for this could be that a file gets imported when doing a bulk update for work/visit status and the file contains null for the `reason` field. This then gets converted into a string, causing `reason` to be saved as "null".
A check has now been added to ensure that a "null" string doesn't get sent in the JSON payload. If the instance contains a "null" string then this simply gets set to `None`. Additionally, the imports for …
=> Prevent Null Strings in Serialization

.github/workflows/deploy.yml, deploy/README.md, deploy/config/deploy.production.yml, deploy/config/deploy.staging.yml, deploy/config/deploy.yml
Added Log Groups for staging and production services.
Cloudwatch Log Group Names
- commcare-connect-web
- commcare-connect-celery
- commcare-connect-staging-web
- commcare-connect-staging-celery
Stream names are generated from container type now (web, celery) and container_id now.
=> Cloudwatch Log Groups and Stream Names

commcare_connect/opportunity/views.py
This change resolve the 404 error when pm invites user in a managed opportunity - `get_opportunity_or_404`
[CCCT-1191](https://dimagi.atlassian.net/browse/CCCT-1191)
Tested Locally
No QA
[CCCT-1191]: https://dimagi.atlassian.net/browse/CCCT-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [New UI] Fixed Opportunity 404 on user_invite

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_forms.py, commcare_connect/opportunity/views.py
This PR fixes a bug in Add worker form related views. The filter_country and filter_credential fields were removed from the form but not from the views which led to 500 errors. 
This PR also removes all references to credential workflow from add_connect_users since those fields are now removed.
Fixed the test cases, tested locally.
Fixed Test cases.
=> Fix Add Worker Forms bug

commcare_connect/opportunity/helpers.py, commcare_connect/opportunity/tables.py, commcare_connect/opportunity/views.py, commcare_connect/templates/tailwind/base_table.html, commcare_connect/templates/tailwind/components/worker_page/profile.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/dashboard.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/opportunity_delivery_stat.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/opportunity_funnel_progress.html, commcare_connect/templates/tailwind/pages/opportunity_dashboard/opportunity_resource_modal.html
This pr address following issues:- 
[CCCT-1277](https://dimagi.atlassian.net/browse/CCCT-1277)
https://dimagi.atlassian.net/browse/QA-7760
https://dimagi.atlassian.net/browse/QA-7760
https://dimagi.atlassian.net/browse/QA-7772
https://dimagi.atlassian.net/browse/QA-7774
https://dimagi.atlassian.net/browse/QA-7778
https://dimagi.atlassian.net/browse/CCCT-1178
1. Remove duplicates in Delivery tab progress bar
2. Reconcile Total Services Delivered in Opp Dashboard with Total Row in Delivery Tab
3. Change to Services Delivered Progress Bar. Replace the Total Services Delivered numbers at the end of the progress bars with the actual ‘Approved’ number and ‘Rejected’ number
4. Remove the Max Budget figure from the end of the progress bar
5. Replace 750(earned amount) with actual paid amount
6. …
=> [NEW UI] - Minor changes on opp dashboard and worker list

commcare_connect/opportunity/tables.py
The flag reason column has been added to the PM review sheet export:
Link to ticket [here](https://dimagi.atlassian.net/browse/CI-94).
This PR simply adds the `flag_reason` field from the `UserVisit` model for export in PM review sheets. Adding this column allows a user to know why the visit was flagged and better understand the corresponding justification without having to match those visits with the User Visits sheet.
- Single line change that only adds a single extra column to PM review sheet exports
N/A
No QA planned.
=> Flag Reason Column

commcare_connect/opportunity/export.py, commcare_connect/opportunity/tasks.py, commcare_connect/opportunity/tests/test_export.py
Refactored the User Visit Export to have pagination on the queryset to reduce the amount of visits that are held in memory at a point of time.
Refactored the code for flattening the json in dataset that also aggregated headers. This code now runs for all deliver units in the current export once at the start and aggregates all the headers including headers generated from flattened json for the dataset. 
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-881)
I have done testing locally for 50000 user visits with a 10x10 form json. 
- Base
- peak mem 3,207,889.62 KiB (3.05 GiB)
- final mem 1,950,386.31 KiB 
- Refactored with Pagination, no library changes
- peak mem 882,964.33 KiB (0.84 GiB) (1/4 usage compared to before)
- final mem 819,649.30 KiB 
This code has good automated test …
=> Export Improvements for User Visit export.

commcare_connect/form_receiver/tests/test_receiver_integration.py, commcare_connect/opportunity/utils/completed_work.py, commcare_connect/opportunity/visit_import.py
This PR include fixes for the below issues
- Duplicate Visits were causing auto-approved CompletedWorks to become pending for managed opportunities.
- Rejected completed works cannot be approved automatically as they were excluded from the update_payment_accrued function.
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1267)
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1266)
[Ticket Link](https://dimagi.atlassian.net/browse/CCCT-1287)
Tested on staging.
=> Fixes for status sync issues

commcare_connect/opportunity/admin.py
This PR enhances the Django admin for CommCareApp by:
- Displaying linked Opportunity IDs in the app list view.
- Enabling search by cc_domain, name, and cc_app_id for easier lookup.
This will help admins quickly identify where an app is used and filter apps by their associated CommCare domain.
=> Commcare app to admin seach and linked opp ids

commcare_connect/users/urls.py, commcare_connect/users/views.py
Connect part of https://github.com/dimagi/connect-id/pull/131
Adds two views, one to check if a phone number has been invited to a connect opportunity. One to resend invites to a phone number. Only invites that were not previously sent, because the user was not found, are sent.
Both views are unused except in new workflows
=> add invite views

commcare_connect/users/views.py
`ClientProtectedResourceMixin` [allows](https://django-oauth-toolkit.readthedocs.io/en/latest/views/mixins.html#oauth2_provider.views.mixins.ClientProtectedResourceMixin) passing client credentials via basic auth rather than fetching a token, which is how `ConnectID` was setup to pass those credentials.
=> update auth to allow passing client credentials as password

commcare_connect/opportunity/views.py
Override get_object in OpportunityDashboard to fetch opportunity using get_opportunity_or_404 with pk and org_slug.
https://dimagi.atlassian.net/browse/CI-124
Tested locally
=> Custom get_object logic for OpportunityDashboard

commcare_connect/organization/tasks.py, commcare_connect/templates/organization/organization_home.html
[Ticket](https://dimagi.atlassian.net/browse/CCCT-1377)
This PR is for temporarily disabling the ability on Connect for adding credentials to users. This is until the new worker history feature has been rolled out properly. 
Simple change. Tests still pass.
No new tests
No QA planned
=> Disable credentials on connect

commcare_connect/templates/opportunity/user_visit_verification_table.html
A bug is fixed where the selected date "jumps" to the previous day in timezones west of UTC.
The bug is being reproduced in .gif below:
The fixed behaviour can be seen in the .gif below:
[Ticket](https://dimagi.atlassian.net/browse/CI-152)
This PR fixes an issue where the browser takes the local timezone into account when populating a javascript `Date` object, given a date from the request. The problematic behaviour is that, if the local timezone is west of UTC the date picker jumps back 1 day.
The fix is simple: force the date object that is being populated to use the zero-th hour with the date from the request instead of taking the local timezone into account and potentially jumping back to the previous day.
Example of problem:
I set my timezone to Atlantic Daylight Time (UTC-03) and …
=> Append zero-hour time so browser time is ignored

.github/workflows/ci.yml, commcare_connect/opportunity/tasks.py
This task is only supposed to run once per month to get the rates, but when it fails and a rate is missing, it gets called over and over causing us to hit our limits on openexchangerates. This PR does two things to handle failures a bit better
1) limits our requests to once per day (per URL, which changes monthly) by caching the result.
2) reports currencies that aren't found to sentry, but continues processing the rest to prevent a bad code from causing overall failure. 
It also fixes a bug with the loop variables.
I had to switch the test runner to use prod requirements in order to avoid an import error for `sentry_sdk`. We could probably also move it to a different file that isn't called during tests, but there doesn't seem to be a huge downside in making our tests closer to the prod …
=> currency handling improvements

commcare_connect/connect_id_client/exceptions.py, commcare_connect/connect_id_client/main.py, commcare_connect/templates/pages/connect_user_otp.html, commcare_connect/users/forms.py, commcare_connect/users/tests/test_forms.py, commcare_connect/users/tests/test_views.py, commcare_connect/users/urls.py, commcare_connect/users/views.py
This PR adds a view at `<base_url>/users/connect_user_otp/` which allows a staff user to request an OTP for a given phone number.
Here's the page:
When an OTP is received it will be displayed to the user using django's built-in messaging alerts:
[Ticket](https://dimagi.atlassian.net/browse/CCCT-1522)
Also relates to [this PersonalID PR](https://github.com/dimagi/connect-id/pull/163).
Did local testing (except making the call to ConnectID server). Will test on staging as well.
No automated tests added.
No formal QA planned.
=> Add "staff" view for manually requesting OTP 

commcare_connect/opportunity/forms.py, commcare_connect/opportunity/tests/test_views.py
No user facing change
When the `end_date` of an `OpportunityClaim` is updated, the corresponding end_date in `OpportunityClaimLimit` should also be updated.
[CCCT-915](https://dimagi.atlassian.net/browse/CCCT-915)
Just added a query to update the `end_date` of `OpportunityClaimLimit` so it is pretty much safe.
Updated the tests
No QA
[CCCT-915]: https://dimagi.atlassian.net/browse/CCCT-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update OpportunityClaimLimit end_date

commcare_connect/opportunity/views.py
The following widgets on the opportunity dashboard have been updated to only show whole numbers:
- Max Connect Workers
- Max Service Deliveries
- Approved / Rejected percent values in the "Verification" box
- Earned / Paid percentages in the “Payments to Connect Workers”
**Before:**
**After:**
The numbers shown on these widgets will always be rounded down.
Link to ticket [here](https://dimagi.atlassian.net/browse/CCCT-1673).
- Local testing
None.
No QA planned.
=> Only Show Whole Numbers on Opportunity Dashboard

commcare_connect/utils/sms.py
Similar connect PR https://github.com/dimagi/connect-id/pull/183
Twilio doesn't support international long codes for SMS to the UK, this changes to use "ConnectID" as the sender.
We use the same approach for multiple other countries, and SMS are already failing so risk is low.
=> update uk sender

commcare_connect/reports/helpers.py
- Fixed average top paid flws metric on Delivery Stats dashboard to be an average instead of a sum.
[Ticket Link](https://dimagi.atlassian.net/browse/CI-270)
- Tested Locally
- This code has test coverage.
- None
=> Fix average top paid flws metric to be average instead of sum

commcare_connect/templates/components/worker_page/fetch_flag_counts.html
No user facing change
This PR addresses an issue on the Deliveries tab where unnecessary bulk requests were being made on page load to fetch flag counts for all delivery rows.
With this update, the UI now lazy-loads flag counts: the API call to fetch a row's flag count is triggered only when the user clicks on the flag count number for that specific cell. This change ensures that only the required data is fetched, significantly reducing the number of API calls and improving performance.
This is what’s happening right now: - [Opp Link prod](https://connect.dimagi.com/a/dimagi-gw-chc-2024-2025/opportunity/411/workers/deliver/?sort=-last_active)
<video width="1719" height="906" src="https://github.com/user-attachments/assets/affa86d2-33cb-4aa9-a609-c59013955a0c" />
After Fix: [Opp Link …
=> Avoid bulk requests on page load.
